IMAGE_PATH = './inp_1.jpg'
DEVICE = 'cpu'
SAVED_IMAGE_DIR = './saved_images/'

VARIATION_LOSS_WEIGHT = 0.00001
FEATURE_LOSS_WEIGHT = 1

INPUT_IMAGE_SIZE = 500
LEARNING_RATE = 0.01
NUM_EPOCHS = 40
